# declare version
version: '3.8'

# all services
services:
# nginx
    nginx:
      container_name: nginx
      build: requirement/nginx
      image: nginx:v_final
      depends_on:
        - wordpress
      networks:
        - docker_network
      ports:
        - "443:443"
      volumes:
        - wordpress_data:/var/www/html/wordpress
      restart: always

# wordpress
    wordpress:
      container_name: wordpress
      build: requirement/wordpress
      image: wordpress:v_final
      depends_on:
        - mariadb
      networks:
        - docker_network
      volumes:
        - wordpress_data:/var/www/html/wordpress
      env_file:
        - .env
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      restart: always

# mariadb
    mariadb:
      container_name: mariadb
      build: requirement/mariadb
      image: mariadb:v_final
      env_file:
        - .env
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      volumes:
        - db_data:/var/lib/mysql
      # it allows the access which share same network(docker_network)
      networks:
        - docker_network
      restart: always

# network setting
networks:
    docker_network:
      driver: bridge

# volumes setting (data)
volumes:
   db_data:
     driver: local
     driver_opts:
        type: none
        device: /home/donghank/data/mysql
        o: bind
   wordpress_data:
      driver: local
      driver_opts:
        type: none
        device: /home/donghank/data/wordpress
        o: bind
