# declare version
version: '3'

# all services
services:
# nginx part
    nginx:
      container_name: nginx
      build: requirement/nginx
      image: nginx:v_final
      depends_on:
        - wordpress
      networks:
        - docker_network
      ports:
        - "443:443"
      volumes:
        - wordpress_data:/var/www/html/wordpress
      restarts: always
#mariadb
    mariadb:
      container_name: mariadb
      build: requirement/mariadb
      image: mariadb:v_final
      environment:
        - MYSQL_DATABASE = ${MYSQL_DATABASE}
        - MYSQL_USER = ${MYSQL_USER}
        - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD = ${MYSQL_ROOT_PASSWORD}
      volumes:
        - db_data:/var/lib/mysql
      # it allows the access which share same network(docker_network)
      networks:
        - docker_network
      restarts: always
